#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Jun 06, 2018 11:35:13 AM

import sys
import os
import webbrowser
import time

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import gui_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = shittool (root)
    gui_support.init(root, top)
    root.mainloop()

w = None
def create_shittool(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = shittool (w)
    gui_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_shittool():
    global w
    w.destroy()
    w = None


class shittool:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        top.geometry("406x300+716+331")
        top.title("ShitTool!!")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.moveto = Label(top)
        self.moveto.place(relx=0.37, rely=0.27, height=21, width=94)
        self.moveto.configure(activebackground="#f9f9f9")
        self.moveto.configure(activeforeground="black")
        self.moveto.configure(background="#d9d9d9")
        self.moveto.configure(disabledforeground="#a3a3a3")
        self.moveto.configure(foreground="#000000")
        self.moveto.configure(highlightbackground="#d9d9d9")
        self.moveto.configure(highlightcolor="black")
        self.moveto.configure(text='''Move to folder:''')

        self.gta = Button(top)
        self.gta.place(relx=0.3, rely=0.4, height=24, width=35)
        self.gta.configure(activebackground="#d9d9d9")
        self.gta.configure(activeforeground="#000000")
        self.gta.configure(background="#d9d9d9")
        self.gta.configure(disabledforeground="#a3a3a3")
        self.gta.configure(foreground="#000000")
        self.gta.configure(highlightbackground="#d9d9d9")
        self.gta.configure(highlightcolor="black")
        self.gta.configure(pady="0")
        self.gta.configure(text='''GTA''')
        self.gta.configure(command=self.movetogta)

        self.backup = Button(top)
        self.backup.place(relx=0.57, rely=0.4, height=24, width=52)
        self.backup.configure(activebackground="#d9d9d9")
        self.backup.configure(activeforeground="#000000")
        self.backup.configure(background="#d9d9d9")
        self.backup.configure(disabledforeground="#a3a3a3")
        self.backup.configure(foreground="#000000")
        self.backup.configure(highlightbackground="#d9d9d9")
        self.backup.configure(highlightcolor="black")
        self.backup.configure(pady="0")
        self.backup.configure(text='''Backup''')
        self.backup.configure(command=self.movetobackup)

        self.situationtext = Label(top)
        self.situationtext.place(relx=0.0, rely=0.93, height=21, width=59)
        self.situationtext.configure(activebackground="#f9f9f9")
        self.situationtext.configure(activeforeground="black")
        self.situationtext.configure(background="#d9d9d9")
        self.situationtext.configure(disabledforeground="#a3a3a3")
        self.situationtext.configure(foreground="#000000")
        self.situationtext.configure(highlightbackground="#d9d9d9")
        self.situationtext.configure(highlightcolor="black")
        self.situationtext.configure(text='''Situation:''')

        self.statustext = Label(top)
        self.statustext.place(relx=0.17, rely=0.93, height=21, width=326)
        self.statustext.configure(activebackground="#f9f9f9")
        self.statustext.configure(activeforeground="black")
        self.statustext.configure(background="#d9d9d9")
        self.statustext.configure(disabledforeground="#a3a3a3")
        self.statustext.configure(foreground="#000000")
        self.statustext.configure(highlightbackground="#d9d9d9")
        self.statustext.configure(highlightcolor="black")
        self.statustext.configure(width=326)

        self.start = Button(top)
        self.start.place(relx=0.17, rely=0.6, height=24, width=64)
        self.start.configure(activebackground="#d9d9d9")
        self.start.configure(activeforeground="#000000")
        self.start.configure(background="#d9d9d9")
        self.start.configure(disabledforeground="#a3a3a3")
        self.start.configure(foreground="#000000")
        self.start.configure(highlightbackground="#d9d9d9")
        self.start.configure(highlightcolor="black")
        self.start.configure(pady="0")
        self.start.configure(text='''Start GTA''')
        self.start.configure(command=self.startgame)

        self.check = Button(top)
        self.check.place(relx=0.02, rely=0.83, height=24, width=45)
        self.check.configure(activebackground="#d9d9d9")
        self.check.configure(activeforeground="#000000")
        self.check.configure(background="#d9d9d9")
        self.check.configure(disabledforeground="#a3a3a3")
        self.check.configure(foreground="#000000")
        self.check.configure(highlightbackground="#d9d9d9")
        self.check.configure(highlightcolor="black")
        self.check.configure(pady="0")
        self.check.configure(text='''Check''')
        self.check.configure(command=self.findpath)

        self.gtafolder = Button(top)
        self.gtafolder.place(relx=0.39, rely=0.6, height=24, width=74)
        self.gtafolder.configure(activebackground="#d9d9d9")
        self.gtafolder.configure(activeforeground="#000000")
        self.gtafolder.configure(background="#d9d9d9")
        self.gtafolder.configure(disabledforeground="#a3a3a3")
        self.gtafolder.configure(foreground="#000000")
        self.gtafolder.configure(highlightbackground="#d9d9d9")
        self.gtafolder.configure(highlightcolor="black")
        self.gtafolder.configure(pady="0")
        self.gtafolder.configure(text='''GTA Folder''')
        self.gtafolder.configure(command=self.opengtafolder)

        self.backupfolder = Button(top)
        self.backupfolder.place(relx=0.64, rely=0.6, height=24, width=91)
        self.backupfolder.configure(activebackground="#d9d9d9")
        self.backupfolder.configure(activeforeground="#000000")
        self.backupfolder.configure(background="#d9d9d9")
        self.backupfolder.configure(disabledforeground="#a3a3a3")
        self.backupfolder.configure(foreground="#000000")
        self.backupfolder.configure(highlightbackground="#d9d9d9")
        self.backupfolder.configure(highlightcolor="black")
        self.backupfolder.configure(pady="0")
        self.backupfolder.configure(text='''Backup Folder''')
        self.backupfolder.configure(command=self.openbackupfolder)
        

    def startgame(self):
        webbrowser.open("steam://rungameid/271590")
        self.statustext.configure(text='''Starting GTA...''')
        time.sleep(5)
        self.statustext.configure(text='''GTA should be started''')
	    
    def findpath(self):
        
        OpenIVlog = os.path.exists("C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/OpenIV.log")
        OpenIVasi = os.path.exists("C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/OpenIV.asi")
        ScriptHookVdll = os.path.exists("C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/ScriptHookV.dll")
        ScriptHookVlog = os.path.exists("C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/ScriptHookV.log")
        ScriptHookVDotNetasi = os.path.exists("C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/ScriptHookVDotNet.asi")
        ScriptHookVDotNet2dll = os.path.exists("C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/ScriptHookVDotNet2.dll")
        ScriptHookVDotNet2log = os.path.exists("C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/ScriptHookVDotNet2.log")
        EnhancedNativeTrainerasi = os.path.exists("C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/EnhancedNativeTrainer.asi")        
        GTSLibasi = os.path.exists("C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/GTSLib.asi")
        RespawnFixasi = os.path.exists("C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/RespawnFix.asi")
        RespawnFixini = os.path.exists("C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/RespawnFix.ini")
        dinput8dll = os.path.exists("C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/dinput8.dll")
        openCameraVasi = os.path.exists("C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/openCameraV.asi")
        openCameraVlog = os.path.exists("C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/openCameraV.log")

        OpenIVlog1 = os.path.exists("C:/Users/horlickc_/Documents/gtamodbackup/OpenIV.log")
        OpenIVasi1 = os.path.exists("C:/Users/horlickc_/Documents/gtamodbackup/OpenIV.asi")
        ScriptHookVdll1 = os.path.exists("C:/Users/horlickc_/Documents/gtamodbackup/ScriptHookV.dll")
        ScriptHookVlog1 = os.path.exists("C:/Users/horlickc_/Documents/gtamodbackup/ScriptHookV.log")
        ScriptHookVDotNetasi1 = os.path.exists("C:/Users/horlickc_/Documents/gtamodbackup/ScriptHookVDotNet.asi")
        ScriptHookVDotNet2dll1 = os.path.exists("C:/Users/horlickc_/Documents/gtamodbackup/ScriptHookVDotNet2.dll")
        ScriptHookVDotNet2log1 = os.path.exists("C:/Users/horlickc_/Documents/gtamodbackup/ScriptHookVDotNet2.log")
        EnhancedNativeTrainerasi1 = os.path.exists("C:/Users/horlickc_/Documents/gtamodbackup/EnhancedNativeTrainer.asi")        
        GTSLibasi1 = os.path.exists("C:/Users/horlickc_/Documents/gtamodbackup/GTSLib.asi")
        RespawnFixasi1 = os.path.exists("C:/Users/horlickc_/Documents/gtamodbackup/RespawnFix.asi")
        RespawnFixini1 = os.path.exists("C:/Users/horlickc_/Documents/gtamodbackup/RespawnFix.ini")
        dinput8dll1 = os.path.exists("C:/Users/horlickc_/Documents/gtamodbackup/dinput8.dll")
        openCameraVasi1 = os.path.exists("C:/Users/horlickc_/Documents/gtamodbackup/openCameraV.asi")
        openCameraVlog1 = os.path.exists("C:/Users/horlickc_/Documents/gtamodbackup/openCameraV.log")

        alllist = [OpenIVlog,OpenIVasi,ScriptHookVdll,ScriptHookVlog,ScriptHookVDotNetasi,ScriptHookVDotNet2dll,ScriptHookVDotNet2log,EnhancedNativeTrainerasi,GTSLibasi,RespawnFixasi,RespawnFixini,dinput8dll,openCameraVasi,openCameraVlog]
        alllist2 = [OpenIVlog1,OpenIVasi1,ScriptHookVdll1,ScriptHookVlog1,ScriptHookVDotNetasi1,ScriptHookVDotNet2dll1,ScriptHookVDotNet2log1,EnhancedNativeTrainerasi1,GTSLibasi1,RespawnFixasi1,RespawnFixini1,dinput8dll1,openCameraVasi1,openCameraVlog1]
        for i in alllist:
            for u in alllist2:
                if i:
                    self.statustext.configure(text='''All files are in GTA folder. Mods are able''')
                elif u:
                    self.statustext.configure(text='''All files are in backup folder. Online is able''')
                else:
                    self.statustext.configure(text='''File(s) is/are not in the same folder''')

    def movetobackup(self):
        def move(a, b):
            return os.rename(a, b)

        try:
            mods = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/mods"
            nmods = "C:/Users/horlickc_/Documents/gtamodbackup/mods"
            move(mods, nmods)
            
            scripts = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/scripts"
            nscripts = "C:/Users/horlickc_/Documents/gtamodbackup/scripts"
            move(scripts, nscripts)

            dinput8 = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/dinput8.dll"
            ndinput8 = "C:/Users/horlickc_/Documents/gtamodbackup/dinput8.dll"
            move(dinput8, ndinput8)

            opencamerav = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/openCameraV.asi"
            nopencamerav = "C:/Users/horlickc_/Documents/gtamodbackup/openCameraV.asi"
            move(opencamerav, nopencamerav)
           
            tnopencamerav = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/openCameraV.log"
            ntnopencamerav = "C:/Users/horlickc_/Documents/gtamodbackup/openCameraV.log"
            move(tnopencamerav, ntnopencamerav)
     
            openiv = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/OpenIV.asi"
            nopeniv = "C:/Users/horlickc_/Documents/gtamodbackup/OpenIV.asi"
            move(openiv, nopeniv)
            
            topeniv = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/OpenIV.log"
            ntopeniv = "C:/Users/horlickc_/Documents/gtamodbackup/OpenIV.log"
            move(topeniv, ntopeniv)

            shv = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/ScriptHookV.dll"
            nshv = "C:/Users/horlickc_/Documents/gtamodbackup/ScriptHookV.dll"
            move(shv, nshv)
            
            tshv = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/ScriptHookV.log"
            ntshv = "C:/Users/horlickc_/Documents/gtamodbackup/ScriptHookV.log"
            move(tshv, ntshv)
            
            shvdn = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/ScriptHookVDotNet.asi"
            nshvdn = "C:/Users/horlickc_/Documents/gtamodbackup/ScriptHookVDotNet.asi"
            move(shvdn, nshvdn)
            
            dshvdn = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/ScriptHookVDotNet2.dll"
            ndshvdn = "C:/Users/horlickc_/Documents/gtamodbackup/ScriptHookVDotNet2.dll"
            move(dshvdn, ndshvdn)
            
            tshvdn = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/ScriptHookVDotNet2.log"
            ntshvdn = "C:/Users/horlickc_/Documents/gtamodbackup/ScriptHookVDotNet2.log"
            move(tshvdn, ntshvdn)
            
            ent = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/EnhancedNativeTrainer.asi"
            nent = "C:/Users/horlickc_/Documents/gtamodbackup/EnhancedNativeTrainer.asi"
            move(ent, nent)

            oi = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/OnlineInteriors.dll"
            noi = "C:/Users/horlickc_/Documents/gtamodbackup/OnlineInteriors.dll"
            move(oi, noi)

            oiini = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/OnlineInteriors.ini"
            noiini = "C:/Users/horlickc_/Documents/gtamodbackup/OnlineInteriors.ini"
            move(oiini, noiini)

            opi = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/OpenInteriors.asi"
            nopi = "C:/Users/horlickc_/Documents/gtamodbackup/OpenInteriors.asi"
            move(opi, nopi)

            opiini = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/OpenInteriors.ini"
            nopiini = "C:/Users/horlickc_/Documents/gtamodbackup/OpenInteriors.ini"
            move(opiini, nopiini)

            gtslib = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/GTSLib.asi"
            ngtslib = "C:/Users/horlickc_/Documents/gtamodbackup/GTSLib.asi"
            move(gtslib, ngtslib)

            rf = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/RespawnFix.asi"
            nrf = "C:/Users/horlickc_/Documents/gtamodbackup/RespawnFix.asi"
            move(rf, nrf)

            rfini = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/RespawnFix.ini"
            nrfini = "C:/Users/horlickc_/Documents/gtamodbackup/RespawnFix.ini"
            move(rfini, nrfini)

            status = os.path.exists('C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\OpenIV.log')
            if status:
                self.statustext.configure(text='''Files cannot be moved!''')
            else:
                time.sleep(2)
                self.statustext.configure(text='''All files are in backup folder now! You can go online''')

        except:
            self.statustext.configure(text='''No more file to move''')

        

    def movetogta(self):
        def move(a, b):
            return os.rename(b, a)

        try:
            mods = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/mods"
            nmods = "C:/Users/horlickc_/Documents/gtamodbackup/mods"
            move(mods, nmods)
            
            scripts = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/scripts"
            nscripts = "C:/Users/horlickc_/Documents/gtamodbackup/scripts"
            move(scripts, nscripts)

            dinput8 = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/dinput8.dll"
            ndinput8 = "C:/Users/horlickc_/Documents/gtamodbackup/dinput8.dll"
            move(dinput8, ndinput8)

            opencamerav = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/openCameraV.asi"
            nopencamerav = "C:/Users/horlickc_/Documents/gtamodbackup/openCameraV.asi"
            move(opencamerav, nopencamerav)
           
            tnopencamerav = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/openCameraV.log"
            ntnopencamerav = "C:/Users/horlickc_/Documents/gtamodbackup/openCameraV.log"
            move(tnopencamerav, ntnopencamerav)
     
            openiv = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/OpenIV.asi"
            nopeniv = "C:/Users/horlickc_/Documents/gtamodbackup/OpenIV.asi"
            move(openiv, nopeniv)
            
            topeniv = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/OpenIV.log"
            ntopeniv = "C:/Users/horlickc_/Documents/gtamodbackup/OpenIV.log"
            move(topeniv, ntopeniv)

            shv = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/ScriptHookV.dll"
            nshv = "C:/Users/horlickc_/Documents/gtamodbackup/ScriptHookV.dll"
            move(shv, nshv)
            
            tshv = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/ScriptHookV.log"
            ntshv = "C:/Users/horlickc_/Documents/gtamodbackup/ScriptHookV.log"
            move(tshv, ntshv)
            
            shvdn = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/ScriptHookVDotNet.asi"
            nshvdn = "C:/Users/horlickc_/Documents/gtamodbackup/ScriptHookVDotNet.asi"
            move(shvdn, nshvdn)
            
            dshvdn = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/ScriptHookVDotNet2.dll"
            ndshvdn = "C:/Users/horlickc_/Documents/gtamodbackup/ScriptHookVDotNet2.dll"
            move(dshvdn, ndshvdn)
            
            tshvdn = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/ScriptHookVDotNet2.log"
            ntshvdn = "C:/Users/horlickc_/Documents/gtamodbackup/ScriptHookVDotNet2.log"
            move(tshvdn, ntshvdn)
            
            ent = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/EnhancedNativeTrainer.asi"
            nent = "C:/Users/horlickc_/Documents/gtamodbackup/EnhancedNativeTrainer.asi"
            move(ent, nent)

            oi = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/OnlineInteriors.dll"
            noi = "C:/Users/horlickc_/Documents/gtamodbackup/OnlineInteriors.dll"
            move(oi, noi)

            oiini = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/OnlineInteriors.ini"
            noiini = "C:/Users/horlickc_/Documents/gtamodbackup/OnlineInteriors.ini"
            move(oiini, noiini)

            opi = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/OpenInteriors.asi"
            nopi = "C:/Users/horlickc_/Documents/gtamodbackup/OpenInteriors.asi"
            move(opi, nopi)

            opiini = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/OpenInteriors.ini"
            nopiini = "C:/Users/horlickc_/Documents/gtamodbackup/OpenInteriors.ini"
            move(opiini, nopiini)

            gtslib = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/GTSLib.asi"
            ngtslib = "C:/Users/horlickc_/Documents/gtamodbackup/GTSLib.asi"
            move(gtslib, ngtslib)

            rf = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/RespawnFix.asi"
            nrf = "C:/Users/horlickc_/Documents/gtamodbackup/RespawnFix.asi"
            move(rf, nrf)

            rfini = "C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/RespawnFix.ini"
            nrfini = "C:/Users/horlickc_/Documents/gtamodbackup/RespawnFix.ini"
            move(rfini, nrfini)

            status = os.path.exists('C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\OpenIV.log')
            if status:
                time.sleep(2)
                self.statustext.configure(text='''All files are in GTA folder now! You can play mods''')
            else:
                self.statustext.configure(text='''Files cannot be moved!''')

        except:
            self.statustext.configure(text='''No more file to move''')

    def opengtafolder(self):
        os.startfile("C:/Program Files (x86)/Steam/steamapps/common/Grand Theft Auto V/")
        
    def openbackupfolder(self):
        os.startfile("C:/Users/horlickc_/Documents/gtamodbackup/")
    

if __name__ == '__main__':
    vp_start_gui()



